services:
  - type: web
    name: ludo-yassou
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: node server.js
    plan: free
    envVars:
      - key: PORT
        value: 10000
